### ISSUE TITLE
Snapshots found but no results

### ISSUE THREAD

**Issue by BinaryScary** [mhmdiaa/chronos#2]
The goroutine at [main.go:93](https://github.com/mhmdiaa/chronos/blob/8b84e6f46be225fdfca7435ce513b203942c58d8/main.go#L93) seems to exit early resulting in no output (I have no clue why), tested on both mac os and ubuntu 20.04, removing the goroutine outputs results.

**Comment by mhmdiaa** [comment]
Hi! I tried to reproduce this but it's working normally on my end. Could you share the exact command you used? Also the output that you got when you removed the goroutine may be helpful.

**Comment by mhmdiaa** [comment]
Closed for inactivity.
